# Generated by Django 2.1.7 on 2019-03-06 16:13

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ad_analytics.models.ads
import ad_analytics.models.company
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to=ad_analytics.models.ads.get_image_path)),
                ('target_url', models.TextField()),
                ('impressions_count', models.BigIntegerField(default=0)),
                ('clicks_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('monthly_budget', models.IntegerField(null=True)),
                ('blacklisted_site_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('site_url', models.TextField()),
                ('cost_per_click_usd', models.DecimalField(decimal_places=10, max_digits=20)),
                ('user_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user_ip', models.CharField(max_length=124)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_analytics.Ads')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to=ad_analytics.models.company.get_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('site_url', models.TextField()),
                ('cost_per_impression_usd', models.DecimalField(decimal_places=10, max_digits=20)),
                ('user_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user_ip', models.CharField(max_length=124)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_analytics.Ads')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ad_analytics.Company'),
        ),
        migrations.AddField(
            model_name='ads',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_analytics.Campaign'),
        ),
    ]
