# Generated by Django 2.1.7 on 2019-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0002_auto_20190307_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Running'), (2, 'Paused'), (3, 'Archived')], default=0),
        ),
    ]
