# Generated by Django 2.1.7 on 2019-03-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0004_auto_20190315_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='name',
        ),
    ]
