# Generated by Django 2.1.7 on 2019-03-15 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0005_remove_click_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impression',
            name='name',
        ),
        migrations.AddField(
            model_name='impression',
            name='seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
