# Generated by Django 2.1.7 on 2019-03-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0006_auto_20190315_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_companies', to='ad_analytics.Employee'),
        ),
    ]
