# Generated by Django 2.1.7 on 2019-04-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0007_company_ceo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='cost_per_click_usd',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
