# Generated by Django 2.1.7 on 2019-04-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0008_auto_20190405_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='clicked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ad_analytics.Campaign'),
        ),
        migrations.AlterField(
            model_name='click',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ad_analytics.Ads'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ad_analytics.Ads'),
        ),
    ]
