# Generated by Django 2.1.7 on 2019-05-13 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0011_auto_20190513_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCollaborators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ad_analytics_campaign_collaborators',
            },
        ),
        migrations.AlterField(
            model_name='campaign',
            name='collaborators',
            field=models.ManyToManyField(through='ad_analytics.CampaignCollaborators', to='ad_analytics.Employee'),
        ),
        migrations.AddField(
            model_name='campaigncollaborators',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_analytics.Campaign'),
        ),
        migrations.AddField(
            model_name='campaigncollaborators',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_analytics.Company'),
        ),
        migrations.AddField(
            model_name='campaigncollaborators',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_analytics.Employee'),
        ),
    ]
