# Generated by Django 2.1.7 on 2019-05-13 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0012_auto_20190513_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncollaborators',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_analytics.Company'),
        ),

        migrations.RunSQL("""
        UPDATE ad_analytics_ads
        SET company_id = campaigns.company_id
        FROM ad_analytics_campaign campaigns
        WHERE campaigns.id = ad_analytics_ads.campaign_id;
        """),

        migrations.RunSQL("""
        UPDATE ad_analytics_click
        SET company_id = ads.company_id
        FROM ad_analytics_ads ads
        WHERE ads.id = ad_analytics_click.ads_id;
        """),

        migrations.RunSQL("""
        UPDATE ad_analytics_impression
        SET company_id = ads.company_id
        FROM ad_analytics_ads ads
        WHERE ads.id = ad_analytics_impression.ads_id;
        """),

        migrations.RunSQL("""
        UPDATE ad_analytics_campaign_collaborators
        SET company_id = campaigns.company_id
        FROM ad_analytics_campaign campaigns
        WHERE campaigns.id = ad_analytics_campaign_collaborators.campaign_id;
        """),
    ]
