# Generated by Django 2.1.7 on 2019-05-13 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0012_auto_20190513_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncollaborators',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_analytics.Company'),
        )
    ]
