# Generated by Django 2.1.7 on 2019-08-21 23:11

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('ad_analytics', '0014_auto_20190821_2303'),
    ]

    operations = [
        migrations.RunSQL("SELECT create_reference_table('auth_user')"),
        migrations.RunSQL("SELECT create_distributed_table('ad_analytics_company', 'id')"),
        migrations.RunSQL("SELECT create_distributed_table('ad_analytics_campaign', 'company_id')"),
        migrations.RunSQL("SELECT create_distributed_table('ad_analytics_ads', 'company_id')"),
        migrations.RunSQL("SELECT create_distributed_table('ad_analytics_click', 'company_id')"),
        migrations.RunSQL("SELECT create_distributed_table('ad_analytics_impression', 'company_id')"),
        migrations.RunSQL("SELECT create_distributed_table('ad_analytics_employee', 'company_id');"),
        migrations.RunSQL("SELECT create_distributed_table('ad_analytics_campaign_collaborators', 'company_id');"),

    ]
