# Generated by Django 2.1.7 on 2019-05-14 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0015_primarykey'),
    ]

    operations = [
        migrations.RunSQL("""
        ALTER TABLE ad_analytics_campaign_collaborators DROP CONSTRAINT ad_analytics_campaign_co_campaign_id_employee_id_bc477b48_uniq;
        """),

        migrations.AlterUniqueTogether(
            name='campaigncollaborators',
            unique_together={('company', 'employee', 'campaign')},
        ),
    ]
