# Generated by Django 2.1.7 on 2019-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('ad_analytics', '0015_auto_20190514_0020'),
    ]
    operations = [
        migrations.AlterField(
            model_name='ads',
            name='campaign',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ad_analytics.Campaign'),
        ),
        migrations.AlterField(
            model_name='click',
            name='ads',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ad_analytics.Ads'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_companies', to='ad_analytics.Employee'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='ads',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ad_analytics.Ads'),
        ),
        migrations.AlterField(
            model_name='campaigncollaborators',
            name='campaign',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_analytics.Campaign'),
        ),
       migrations.AlterField(
            model_name='campaigncollaborators',
            name='employee',
            field=django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_analytics.Employee'),
        ),
    ]
