# Generated by Django 2.1.7 on 2019-06-27 12:44

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.mixins


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('ad_analytics', '0016_auto_20190627_1244'),
    ]

    operations = [

        migrations.RunSQL("""
        ALTER TABLE ad_analytics_employee DROP CONSTRAINT ad_analytics_employee_user_id_key;
        """),

        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'user')},
        ),

        migrations.RunSQL("""
        SELECT create_distributed_table('ad_analytics_company', 'id');
        """),

        migrations.RunSQL("""
        SELECT create_distributed_table('ad_analytics_campaign', 'company_id');
        """),

        migrations.RunSQL("""
        SELECT create_distributed_table('ad_analytics_campaign_collaborators', 'company_id');
        """),

        migrations.RunSQL("""
        SELECT create_distributed_table('ad_analytics_ads', 'company_id');
        """),
        migrations.RunSQL("""
        SELECT create_distributed_table('ad_analytics_click', 'company_id');
        """),
        migrations.RunSQL("""
        SELECT create_distributed_table('ad_analytics_impression', 'company_id');
        """),
        migrations.RunSQL("""
        SELECT create_reference_table('auth_user');
        """),

        migrations.RunSQL("""
        SELECT create_distributed_table('ad_analytics_employee', 'company_id');
        """),
    ]
